package com.moh.moh_backend.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.time.LocalDate;

public class MotherRegisterRequest {
    // Auto-generated by midwife, so optional
    public String username;
    @NotBlank public String email;
    public String password; // Auto-generated if not provided
    @NotBlank public String nic;
    @NotBlank public String name;
    public Integer phmAreaId; // Optional - auto-set to midwife's area
    public String address;
    public LocalDate dateOfBirth;
    public String occupation;
    public String contactNumber;
    public String bloodGroup;
    public LocalDate registrationDate;
}